# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# IfNotPresent: only pull the image when it doesnâ€™t already exist on the node.
# Always: always pull the latest version of the image from the container registry.
# Never: there will be no attempts to pull the image.
image:
  repository: ghcr.io/indexdata/reservoir-jit
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

#must be enabled to take effect
okapi-hooks:
  enabled: false
  moduleUrl: http://reservoir:80
  moduleDescriptor: |
    @descriptor@

containerPort: 8080
# envvars passed to the container
env: {}

metrics:
  enabled: true
  prometheusPath: /metrics
  prometheusPort: 9404
  monitor: # if enabled, creates ServiceMonitor or PodMonitor
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    labels: {} # match prom-stack serviceMonitorSelector/podMonitorSelector, usually 'release: <prom-stack-release-name>'
  jmxEnabled: false #jmx port is set via JAVA_OPTS
  jmxDomain: "reservoir"

probes:
  enabled: true

startupProbe:
  enabled: true
  path: /admin/health #light check
  timeoutSeconds: 2
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 60
  initialDelaySeconds: 0

livenessProbe:
  enabled: true
  path: /admin/health #light check
  timeoutSeconds: 2
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  initialDelaySeconds: 0 #uses startup probe

readinessProbe:
  enabled: true
  path: /healthz #deep check
  timeoutSeconds: 3
  periodSeconds: 30
  successThreshold: 2 #flapping
  failureThreshold: 3
  initialDelaySeconds: 0 #uses startup probe

# envvars passed to the container as secretKeyRef, format
# VARIABLE:
#   name: secret-name
#   key: secret-key
envSecrets: {}

# list of secretRef passed to the envFrom
# e.g
# envSecretRefs:
# - db-secrets
envSecretRefs: []

# envvars passed to the container as configMapKeyRef, format
# VARIABLE:
#   name: config-map-name
#   key: config-map-key
envConfigMaps: {}

# list of configMapRef passed to the envFrom
# e.g
# configMapRefs:
# - db-config
configMapRefs: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  httpPort: 80
  metricsPort: 0 # Enabled if >0, don't expose if service is LoadBalancer or NodePort.
                 # If enabled ServiceMonitor is created instead of PodMonitor.

serviceAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
